# Generated by Django 5.2.11 on 2026-02-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0),
        ),
    ]
