# Generated by Django 5.2.11 on 2026-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='Test Company', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.CharField(max_length=200),
        ),
    ]
